include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_I2C_SEND_PROGNAME)
PRIORITY  = $(CONFIG_I2C_SEND_PRIORITY)
STACKSIZE = $(CONFIG_I2C_SEND_STACKSIZE)

MAINSRC = i2c_send.c

include $(APPDIR)/Application.mk
